-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  is_running boolean DEFAULT false,
  mode text DEFAULT 'semi-auto'::text,
  max_bet_per_market numeric DEFAULT 10,
  daily_budget numeric DEFAULT 50,
  daily_spent numeric DEFAULT 0,
  min_edge_threshold numeric DEFAULT 0.15,
  min_confidence text DEFAULT 'medium'::text,
  budget_reset_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  arb_min_profit_pct numeric DEFAULT 0.02,
  arb_max_per_trade numeric DEFAULT 50,
  scan_interval_seconds integer DEFAULT 30,
  arb_mode text DEFAULT 'yes_no'::text,
  CONSTRAINT agent_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event text NOT NULL,
  payload jsonb,
  level text DEFAULT 'info'::text,
  created_at timestamp with time zone DEFAULT now(),
  message text,
  CONSTRAINT agent_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.arb_executions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opportunity_id uuid,
  bet_a_id uuid,
  bet_b_id uuid,
  total_staked numeric NOT NULL DEFAULT 0,
  expected_profit numeric NOT NULL DEFAULT 0,
  actual_profit numeric,
  status text DEFAULT 'open'::text,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  bet_id_a uuid,
  bet_id_b uuid,
  size_usdc numeric,
  expected_profit_usdc numeric,
  market_id text,
  CONSTRAINT arb_executions_pkey PRIMARY KEY (id),
  CONSTRAINT arb_executions_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.arb_opportunities(id),
  CONSTRAINT arb_executions_bet_a_id_fkey FOREIGN KEY (bet_a_id) REFERENCES public.bets(id),
  CONSTRAINT arb_executions_bet_b_id_fkey FOREIGN KEY (bet_b_id) REFERENCES public.bets(id),
  CONSTRAINT arb_executions_bet_id_a_fkey FOREIGN KEY (bet_id_a) REFERENCES public.bets(id),
  CONSTRAINT arb_executions_bet_id_b_fkey FOREIGN KEY (bet_id_b) REFERENCES public.bets(id)
);
CREATE TABLE public.arb_opportunities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  market_id_a text,
  market_id_b text,
  token_id_a text,
  token_id_b text,
  price_a numeric NOT NULL,
  price_b numeric,
  combined_price numeric,
  expected_profit_pct numeric NOT NULL,
  status text DEFAULT 'found'::text,
  found_at timestamp with time zone DEFAULT now(),
  executed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  market_id text,
  CONSTRAINT arb_opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT arb_opportunities_market_id_a_fkey FOREIGN KEY (market_id_a) REFERENCES public.markets(id),
  CONSTRAINT arb_opportunities_market_id_b_fkey FOREIGN KEY (market_id_b) REFERENCES public.markets(id)
);
CREATE TABLE public.bets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  market_id text,
  research_id uuid,
  direction text NOT NULL,
  amount numeric NOT NULL,
  entry_price numeric NOT NULL,
  ai_probability numeric,
  edge numeric,
  status text DEFAULT 'pending'::text,
  outcome_price numeric,
  pnl numeric,
  placed_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  notes text,
  token_id text,
  side text,
  order_id text,
  price numeric,
  size numeric,
  amount_usdc numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bets_pkey PRIMARY KEY (id),
  CONSTRAINT bets_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id),
  CONSTRAINT bets_research_id_fkey FOREIGN KEY (research_id) REFERENCES public.research(id)
);
CREATE TABLE public.markets (
  id text NOT NULL,
  question text NOT NULL,
  category text,
  yes_price numeric,
  no_price numeric,
  volume numeric,
  end_date timestamp with time zone,
  active boolean DEFAULT true,
  last_synced timestamp with time zone DEFAULT now(),
  condition_id text UNIQUE,
  slug text,
  yes_token_id text,
  no_token_id text,
  closed boolean DEFAULT false,
  icon text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT markets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.price_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  market_id text,
  token_id text,
  yes_price numeric,
  no_price numeric,
  spread numeric,
  captured_at timestamp with time zone DEFAULT now(),
  combined_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT price_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT price_snapshots_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id)
);
CREATE TABLE public.research (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  market_id text,
  ai_probability numeric,
  market_probability numeric,
  edge numeric,
  confidence text,
  summary text,
  reasoning text,
  key_factors jsonb,
  risks jsonb,
  recommendation text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT research_pkey PRIMARY KEY (id),
  CONSTRAINT research_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id)
);